application: veji
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: googleapp/static
  
- url: /favicon.ico
  static_files: googleapp/static/favicon.ico
  upload: googleapp/static/favicon.ico

- url: /.*
  script: googleapp/veji.py
  
